'use client';
import {useEffect,useMemo,useState} from 'react';
const tabs=['Markets','Top-Wallet Signals','Consensus','Whales','Price Gaps','Feed Health'];
const coins=['ALL','BTC','ETH','SOL','XRP'];
const usd=(n,d=0)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:d}).format(Number(n||0));
const left=e=>{const s=Math.floor((new Date(e)-Date.now())/1000);return s<=0?'Closing':`${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`};
const age=t=>{const s=Math.max(0,Math.floor(Date.now()/1000-Number(t||0)));return s<60?`${s}s`:`${Math.floor(s/60)}m`};
export default function Home(){
 const [data,setData]=useState({markets:[],signals:[],comparisons:[],spots:{},health:{}}),[tab,setTab]=useState('Markets'),[coin,setCoin]=useState('ALL'),[status,setStatus]=useState('Connecting…'),[updated,setUpdated]=useState(''),[bankroll,setBankroll]=useState(1000),[risk,setRisk]=useState(1),[whale,setWhale]=useState(2500),[minimum,setMinimum]=useState(45);
 const load=async()=>{setStatus('Loading live feeds…');try{const r=await fetch('/api/live',{cache:'no-store'}),j=await r.json();if(!r.ok)throw new Error(j.error||`HTTP ${r.status}`);setData(j);setStatus(`${j.markets.length} markets · ${j.signals.length} wallet signals`);setUpdated(`Updated ${new Date().toLocaleTimeString()}`)}catch(e){setStatus(`Feed error: ${e.message}`)}};
 useEffect(()=>{load();const id=setInterval(load,30000);return()=>clearInterval(id)},[]);
 const markets=useMemo(()=>data.markets.filter(x=>coin==='ALL'||x.coin===coin),[data,coin]);
 const signals=useMemo(()=>data.signals.filter(x=>(coin==='ALL'||x.coin===coin)&&x.score>=minimum).sort((a,b)=>b.score-a.score),[data,coin,minimum]);
 const consensus=useMemo(()=>{const m=new Map();for(const x of signals.filter(x=>x.side==='BUY')){const k=`${x.conditionId}|${x.outcome}`,v=m.get(k)||{...x,wallets:new Set(),total:0};v.wallets.add(x.wallet);v.total+=x.notional;m.set(k,v)}return[...m.values()].map(x=>({...x,walletCount:x.wallets.size})).filter(x=>x.walletCount>=2).sort((a,b)=>b.walletCount-a.walletCount||b.total-a.total)},[signals]);
 const copy=x=>Math.max(1,bankroll*(risk/100)*(.55+x.score/100));
 const Market=({x})=><article className="card market"><div className="row between"><div><span className="symbol">{x.coin}</span> <span className="badge">{x.source} · 15M</span></div><div className="clock">{left(x.end)}</div></div><h3>{x.title}</h3><div className="metrics"><div className="metric"><span>UP / YES</span><b className="green">{(x.yes*100).toFixed(1)}¢</b></div><div className="metric"><span>DOWN / NO</span><b className="red">{((1-x.yes)*100).toFixed(1)}¢</b></div><div className="metric"><span>COINBASE SPOT</span><b>{usd(data.spots[x.coin],2)}</b></div><div className="metric"><span>LIQUIDITY</span><b>{usd(x.liquidity)}</b></div><div className="metric"><span>VOLUME</span><b>{usd(x.volume)}</b></div></div><a className="open" href={x.url} target="_blank">Open Market</a></article>;
 const Signal=({x,kind=''})=><article className={`card ${kind}`}><div className="row between"><div className="row"><span className={`pill ${x.side==='BUY'?'green':'red'}`}>{x.side} {x.outcome}</span><span className="badge">{x.coin} · {age(x.timestamp)} ago</span></div><b className={x.score>=70?'green':x.score>=50?'amber':''}>{x.score}/100</b></div><h3>{x.title}</h3><div className="muted">{x.trader} · rank #{x.rank||'—'}</div><div className="metrics"><div className="metric"><span>PRICE</span><b>{(x.price*100).toFixed(1)}¢</b></div><div className="metric"><span>ORIGINAL SIZE</span><b>{usd(x.notional)}</b></div><div className="metric"><span>SUGGESTED COPY</span><b className="green">{usd(copy(x))}</b></div><div className="metric"><span>POTENTIAL PAYOUT</span><b>{usd(copy(x)/Math.max(.01,x.price))}</b></div><div className="metric"><span>TRADER P&L</span><b>{usd(x.traderPnl)}</b></div></div><a className="open" href={x.url} target="_blank">Verify Price and Open</a></article>;
 let content;
 if(tab==='Markets')content=markets.length?markets.map(x=><Market key={`${x.source}-${x.id}`} x={x}/>):<div className="empty">No active matching 15-minute markets.</div>;
 else if(tab==='Top-Wallet Signals')content=signals.length?signals.map((x,i)=><Signal key={i} x={x}/>):<div className="empty">No signals currently meet the score.</div>;
 else if(tab==='Consensus')content=consensus.length?consensus.map((x,i)=><article className="card consensus" key={i}><div className="row between"><span className="pill green">CONSENSUS {x.outcome}</span><b className="green">{x.walletCount} wallets</b></div><h3>{x.title}</h3><div className="metrics"><div className="metric"><span>TRACKED AMOUNT</span><b>{usd(x.total)}</b></div><div className="metric"><span>SUGGESTED COPY</span><b className="green">{usd(copy(x)*Math.min(2,x.walletCount/2))}</b></div><div className="metric"><span>SCORE</span><b>{x.score}/100</b></div><div className="metric"><span>PRICE</span><b>{(x.price*100).toFixed(1)}¢</b></div><div className="metric"><span>AGE</span><b>{age(x.timestamp)}</b></div></div><a className="open" href={x.url} target="_blank">Open Consensus Market</a></article>):<div className="empty">No current two-wallet consensus.</div>;
 else if(tab==='Whales'){const w=signals.filter(x=>x.notional>=whale);content=w.length?w.map((x,i)=><Signal key={i} x={x} kind="whale"/>):<div className="empty">No tracked trade exceeds {usd(whale)}.</div>}
 else if(tab==='Price Gaps'){const c=data.comparisons.filter(x=>coin==='ALL'||x.coin===coin);content=c.length?c.map((x,i)=><article className="card arb" key={i}><div className="row between"><div><span className="symbol">{x.coin}</span> <span className="badge">MATCHED WINDOW</span></div><div className="clock">{left(x.end)}</div></div><h3>{x.title}</h3><div className="metrics"><div className="metric"><span>POLY UP</span><b>{(x.polyYes*100).toFixed(1)}¢</b></div><div className="metric"><span>KALSHI YES</span><b>{(x.kalshiYes*100).toFixed(1)}¢</b></div><div className="metric"><span>GAP</span><b className="amber">{x.gap.toFixed(1)} pts</b></div><div className="metric"><span>CHEAPER UP</span><b className="green">{x.cheaper}</b></div><div className="metric"><span>SPOT</span><b>{usd(data.spots[x.coin],2)}</b></div></div></article>):<div className="empty">No equivalent windows matched.</div>}
 else content=<div className="health">{Object.entries(data.health).map(([k,v])=><article className="card" key={k}><span className="muted">{k.toUpperCase()}</span><br/><b className={v.ok?'green':'red'}>{v.ok?'ONLINE':'ERROR'}</b><p>{v.detail}</p></article>)}</div>;
 return <main className="wrap"><header><div><div className="eye">LIVE 15-MINUTE CRYPTO INTELLIGENCE</div><h1>Quanta15</h1><p>Markets, top-wallet signals, consensus, whales and cross-platform gaps.</p></div><button onClick={load}>Refresh</button></header><nav className="tabs">{tabs.map(x=><button key={x} className={tab===x?'active':''} onClick={()=>setTab(x)}>{x}</button>)}</nav><nav className="coins">{coins.map(x=><button key={x} className={coin===x?'active':''} onClick={()=>setCoin(x)}>{x}</button>)}</nav><div className="notice"><b>Read before trading:</b> Public trades may appear after execution. Verify the exact window, live order-book price, liquidity, fees and settlement wording.</div><section className="controls"><label>Bankroll $<input type="number" value={bankroll} onChange={e=>setBankroll(+e.target.value)}/></label><label>Risk per signal %<input type="number" step=".1" value={risk} onChange={e=>setRisk(+e.target.value)}/></label><label>Whale threshold $<input type="number" value={whale} onChange={e=>setWhale(+e.target.value)}/></label><label>Minimum score<input type="number" value={minimum} onChange={e=>setMinimum(+e.target.value)}/></label><label>Refresh<input value="Every 30 seconds" disabled/></label></section><div className="status"><i className="dot"></i><b>{status}</b><span>{updated}</span></div><section className="grid">{content}</section></main>
}
