import {NextResponse} from 'next/server';
export const dynamic='force-dynamic'; export const maxDuration=30;
const COINS={BTC:['bitcoin','btc'],ETH:['ethereum','eth'],SOL:['solana','sol'],XRP:['xrp','ripple']};
const SERIES={BTC:'KXBTC15M',ETH:'KXETH15M',SOL:'KXSOL15M',XRP:'KXXRP15M'};
async function get(url){const c=new AbortController(),t=setTimeout(()=>c.abort(),10000);try{const r=await fetch(url,{cache:'no-store',headers:{Accept:'application/json','User-Agent':'Quanta15/1.0'},signal:c.signal});if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);return await r.json()}finally{clearTimeout(t)}}
const arr=v=>Array.isArray(v)?v:(()=>{try{return JSON.parse(v)}catch{return[]}})();
function coinOf(s=''){s=s.toLowerCase();for(const[c,ws]of Object.entries(COINS))if(ws.some(w=>new RegExp(`(^|[^a-z])${w}([^a-z]|$)`,'i').test(s)))return c;return null}
function prob(m){const o=arr(m.outcomes),p=arr(m.outcomePrices).map(Number);let i=o.findIndex(x=>/^(yes|up|higher|above)$/i.test(String(x)));if(i<0)i=0;return p[i]}
function is15(e,m){const txt=`${e.title||''} ${e.slug||''} ${m.question||''} ${m.slug||''}`.toLowerCase();const explicit=/15[\s-]*(minute|min|m)\b/.test(txt)||/up.?or.?down/.test(txt);const st=new Date(m.startDate||e.startDate||0),en=new Date(m.endDate||e.endDate||0),dur=(en-st)/60000;return explicit||(dur>=10&&dur<=20)}
async function poly(health){try{const es=[];for(let off=0;off<1000;off+=200){const p=await get(`https://gamma-api.polymarket.com/events?active=true&closed=false&limit=200&offset=${off}`);es.push(...p);if(p.length<200)break}const now=Date.now(),out=[];for(const e of es)for(const m of e.markets||[]){const coin=coinOf(`${e.title||''} ${m.question||''}`);if(!coin||!is15(e,m))continue;const end=m.endDate||e.endDate,et=new Date(end).getTime();if(!end||et<now-60000||et>now+3600000)continue;const yes=prob(m);if(!Number.isFinite(yes))continue;out.push({source:'Polymarket',id:m.conditionId||m.id,conditionId:m.conditionId,coin,title:m.question||e.title,end,yes,liquidity:Number(m.liquidityNum||m.liquidity||0),volume:Number(m.volumeNum||m.volume||0),url:`https://polymarket.com/event/${e.slug||m.slug}`})}health.polymarket={ok:true,detail:`${out.length} matching markets`};return out}catch(e){health.polymarket={ok:false,detail:e.message};return[]}}
async function kalshi(health){const out=[];let ok=0;await Promise.all(Object.entries(SERIES).map(async([coin,series])=>{try{const j=await get(`https://api.elections.kalshi.com/trade-api/v2/markets?status=open&limit=100&series_ticker=${series}`);ok++;for(const m of j.markets||[]){const end=m.close_time||m.expiration_time,et=new Date(end).getTime();if(!end||et<Date.now()-60000||et>Date.now()+3600000)continue;let yes=Number(m.yes_ask_dollars??m.last_price_dollars??m.yes_ask??m.last_price);if(yes>1)yes/=100;if(!Number.isFinite(yes))continue;out.push({source:'Kalshi',id:m.ticker,coin,title:m.title||m.subtitle||m.ticker,end,yes,liquidity:Number(m.liquidity_dollars||m.liquidity||0),volume:Number(m.volume||0),url:`https://kalshi.com/markets/${String(m.event_ticker||m.ticker).toLowerCase()}`})}}catch{}}));health.kalshi={ok:ok>0,detail:`${out.length} matching markets · ${ok}/4 feeds reached`};return out}
async function spots(health){const out={};let ok=0;await Promise.all(Object.keys(COINS).map(async c=>{try{const j=await get(`https://api.exchange.coinbase.com/products/${c}-USD/ticker`);out[c]=Number(j.price);ok++}catch{}}));health.coinbase={ok:ok>0,detail:`${ok}/4 spot feeds reached`};return out}
async function signals(markets,health){try{const lb=await get('https://data-api.polymarket.com/v1/leaderboard?timePeriod=WEEK&category=OVERALL&orderBy=PNL&limit=20'),leaders=Array.isArray(lb)?lb:[],out=[];await Promise.all(leaders.slice(0,12).map(async l=>{try{const ts=await get(`https://data-api.polymarket.com/trades?user=${l.proxyWallet}&limit=100&takerOnly=true`);for(const t of ts||[]){const m=markets.find(x=>x.conditionId&&(x.conditionId===t.conditionId||x.conditionId===t.market));if(!m)continue;const stamp=Number(t.timestamp||0);if(Date.now()/1000-stamp>900)continue;const price=Number(t.price||0),notional=Number(t.size||0)*price,fresh=Math.max(0,1-(Date.now()/1000-stamp)/900),size=Math.min(1,notional/5000),eff=Math.min(1,Math.max(0,Number(l.pnl||0)/Math.max(1,Number(l.vol||1))*8)),liq=Math.min(1,m.liquidity/25000),score=Math.round(100*(.38*fresh+.25*size+.22*eff+.15*liq));out.push({coin:m.coin,conditionId:m.conditionId,title:t.title||m.title,outcome:t.outcome||'',side:t.side||'BUY',price,size:Number(t.size||0),notional,timestamp:stamp,score,wallet:l.proxyWallet,trader:l.userName||`${l.proxyWallet.slice(0,8)}…`,rank:Number(l.rank||0),traderPnl:Number(l.pnl||0),url:m.url})}}catch{}}));out.sort((a,b)=>b.score-a.score||b.timestamp-a.timestamp);health.wallets={ok:true,detail:`${leaders.length} leaders · ${out.length} matching trades`};return out}catch(e){health.wallets={ok:false,detail:e.message};return[]}}
function compare(p,k){const out=[];for(const x of p){const y=k.find(z=>z.coin===x.coin&&Math.abs(new Date(z.end)-new Date(x.end))<=300000);if(!y)continue;const gap=Math.abs(x.yes-y.yes)*100;out.push({coin:x.coin,title:x.title,end:x.end,polyYes:x.yes,kalshiYes:y.yes,gap,cheaper:x.yes<y.yes?'Polymarket':'Kalshi'})}return out.sort((a,b)=>b.gap-a.gap)}
export async function GET(){const health={};const[p,k,s]=await Promise.all([poly(health),kalshi(health),spots(health)]),sig=await signals(p,health);return NextResponse.json({generatedAt:new Date().toISOString(),markets:[...p,...k].sort((a,b)=>new Date(a.end)-new Date(b.end)),signals:sig,comparisons:compare(p,k),spots:s,health},{headers:{'Cache-Control':'no-store,max-age=0'}})}
